---

# This workflow is used to release Docker images.
# The workflow is triggered manually and allows the user to specify the release version.
# The workflow also creates a GitHub release after the deployment stage if the deployment is successful.
# The workflow requires the following inputs:
# - `release`: The release version to publish.
# The workflow requires several configuration files:
# - Docker build configuration file: `.qubership/docker-build-config.cfg`
#   Example: config/examples/docker-build-config.json
# - GitHub release drafter configuration file: `.github/release-drafter-config.yml`
#   Example: config/examples/release-drafter-config.yml

name: "Docker Images Release"
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version e.g. 1.0.0 (numbers and dots only). "v" prefix will be added automatically.'
        required: true
        type: string

permissions:
  contents: read
run-name: ${{ github.repository }} Release ${{ github.event.inputs.release }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-tag:
    name: "Check if tag exists"
    runs-on: ubuntu-latest
    steps:
      - name: "Check if tag exists"
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@396774180000abdb825cbf150b56cc59c6913db8  # v2.0.5
        with:
          tag-name: 'v${{ inputs.release }}'
          ref: ${{ github.ref }}
          create-tag: false
          check-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  load-docker-build-components:
    needs: [check-tag]
    name: "Load Docker Build Components Configuration"
    runs-on: ubuntu-latest
    outputs:
      component: ${{ steps.load_component.outputs.components }}
      platforms: ${{ steps.load_component.outputs.platforms }}
    env:
      CONFIG_FILE: .qubership/docker-build-config.cfg
    steps:
      - name: "Checkout code"
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: "Load Docker Configuration"
        id: load_component
        run:  |
          verify=$(cat "$GITHUB_WORKSPACE/${CONFIG_FILE}" | jq '
          def verify_structure:
          .components as $components
          | .platforms as $platforms
          | ($components | type == "array")
          and (all($components[]; has("name") and has("file") and has("context")))
          and ($platforms | type == "string");
          verify_structure
          | if . then true else false end
          ')
          if [ ${verify} == 'true' ]; then
            echo "✅ $GITHUB_WORKSPACE/${CONFIG_FILE} file is valid"
            components=$(jq -c ".components" "$GITHUB_WORKSPACE/${CONFIG_FILE}")
            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/${CONFIG_FILE}")
          else
            echo "❗ $GITHUB_WORKSPACE/${CONFIG_FILE} file is invalid"
            echo "❗ $GITHUB_WORKSPACE/${CONFIG_FILE} file is invalid" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          echo "components=${components}" >> $GITHUB_OUTPUT
          echo "platforms=${platforms}" >> $GITHUB_OUTPUT

  create-tag:
    name: "Create Release Tag"
    needs: [load-docker-build-components]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Create Tag"
        uses: netcracker/qubership-workflow-hub/actions/tag-action@396774180000abdb825cbf150b56cc59c6913db8  # v2.0.5
        with:
          tag-name: 'v${{ inputs.release }}'
          ref: ${{ github.ref }}
          create-tag: true
          check-tag: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    name: "${{ matrix.component.name }}"
    needs: [load-docker-build-components, create-tag]
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
    steps:
      - name: "Get version for current component"
        id: get-version
        run: |
          echo "IMAGE_VERSION=${{ inputs.release }}" >> $GITHUB_ENV

      - name: "Docker build and publish"
        uses: netcracker/qubership-workflow-hub/actions/docker-action@396774180000abdb825cbf150b56cc59c6913db8  # v2.0.5
        with:
          ref: 'v${{ inputs.release }}'
          download-artifact: false
          dry-run: false
          component: ${{ toJson(matrix.component) }}
          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  github-release:
    name: "Github Release"
    needs: [docker-build]
    continue-on-error: false
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          ref: v${{ inputs.release }}
          persist-credentials: false

      - name: "Release-drafter"
        uses: netcracker/release-drafter@86f4276a3894b5af70480e826c32fe3648ac6a70  # v1.0.0
        with:
          config-name: release-drafter-config.yml
          publish: true
          name: ${{ inputs.release }}
          tag: v${{ inputs.release }}
          version: ${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
